# Pipeline name convention
name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

# Trigger configuration
trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

# Parameters
parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: snd2Deployment
    type: boolean
    default: true
  - name: snd1Deployment
    type: boolean
    default: true

# Resources
resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: pl-709   # Optional: build specific pipeline branch

# Pipeline template
extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs   # Optional: nodejs (default), dotnet, java
    Type: kubernetes           # Optional: kubernetes (default), npm, functions, nuget
    npmLegacyPeerDeps: false   # Optional: default is false
    dockerFilePath: Dockerfile # Optional default is Dockerfile
    failOnThreshold: moderate  # Optional: moderate (default), low, high, critical
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.snd2Deployment }}
    snd1Deployment: ${{ parameters.snd1Deployment }}
    variableGroupName: ffc-doc-statement-publisher-env-var
    pr_params:
      container.sendCrmFailureMessageEnabled: $(pr_sendCrmFailureMessageEnabled)
      container.deliveryCheckInterval: $(pr_deliveryCheckInterval)
      container.metricsPollingInterval: $(pr_metricsPollingInterval)
      container.notifyApiKey: $(pr_notifyApiKey)
      container.notifyApiKeyLetter: $(pr_notifyApiKeyLetter)
      container.reportingCheckInterval: $(pr_reportingCheckInterval)
    snd1_params:
      container.sendCrmFailureMessageEnabled: $(snd1_sendCrmFailureMessageEnabled)
      container.deliveryCheckInterval: $(snd1_deliveryCheckInterval)
      container.metricsPollingInterval: $(snd1_metricsPollingInterval)
      container.notifyApiKey: $(snd1_notifyApiKey)
      container.notifyApiKeyLetter: $(snd1_notifyApiKeyLetter)
      container.reportingCheckInterval: $(snd1_reportingCheckInterval)
    snd2_params:
      container.sendCrmFailureMessageEnabled: $(snd2_sendCrmFailureMessageEnabled)
      container.deliveryCheckInterval: $(snd2_deliveryCheckInterval)
      container.metricsPollingInterval: $(snd2_metricsPollingInterval)
      container.notifyApiKey: $(snd2_notifyApiKey)
      container.notifyApiKeyLetter: $(snd2_notifyApiKeyLetter)
      container.reportingCheckInterval: $(snd2_reportingCheckInterval)
    dev_params:
      container.sendCrmFailureMessageEnabled: $(dev_sendCrmFailureMessageEnabled)
      container.deliveryCheckInterval: $(dev_deliveryCheckInterval)
      container.metricsPollingInterval: $(dev_metricsPollingInterval)
      container.notifyApiKey: $(dev_notifyApiKey)
      container.notifyApiKeyLetter: $(dev_notifyApiKeyLetter)
      container.reportingCheckInterval: $(dev_reportingCheckInterval)
    test_params:
      container.sendCrmFailureMessageEnabled: $(test_sendCrmFailureMessageEnabled)
      container.deliveryCheckInterval: $(test_deliveryCheckInterval)
      container.metricsPollingInterval: $(test_metricsPollingInterval)
      container.notifyApiKey: $(test_notifyApiKey)
      container.notifyApiKeyLetter: $(test_notifyApiKeyLetter)
      container.reportingCheckInterval: $(test_reportingCheckInterval)
    pre_params:
      container.sendCrmFailureMessageEnabled: $(pre_sendCrmFailureMessageEnabled)
      container.deliveryCheckInterval: $(pre_deliveryCheckInterval)
      container.metricsPollingInterval: $(pre_metricsPollingInterval)
      container.notifyApiKey: $(pre_notifyApiKey)
      container.notifyApiKeyLetter: $(pre_notifyApiKeyLetter)
      container.reportingCheckInterval: $(pre_reportingCheckInterval)
    prd_params:
      container.sendCrmFailureMessageEnabled: $(prd_sendCrmFailureMessageEnabled)
      container.deliveryCheckInterval: $(prd_deliveryCheckInterval)
      container.metricsPollingInterval: $(prd_metricsPollingInterval)
      container.notifyApiKey: $(prd_notifyApiKey)
      container.notifyApiKeyLetter: $(prd_notifyApiKeyLetter)
      container.reportingCheckInterval: $(prd_reportingCheckInterval)
