const JANUARY = 0
const FIRST_DAY_OF_MONTH = 1
const YEAR_START_MONTH = 0
const YEAR_START_DAY = 1

const END_OF_DAY_HOUR = 23
const END_OF_DAY_MINUTE = 59
const END_OF_DAY_SECOND = 59
const END_OF_DAY_MILLISECOND = 999

const MONTH_INDEX_OFFSET = 1
const MONTHS_PER_YEAR = 12

module.exports = {
  JANUARY,
  FIRST_DAY_OF_MONTH,
  YEAR_START_MONTH,
  YEAR_START_DAY,
  END_OF_DAY_HOUR,
  END_OF_DAY_MINUTE,
  END_OF_DAY_SECOND,
  END_OF_DAY_MILLISECOND,
  MONTH_INDEX_OFFSET,
  MONTHS_PER_YEAR
}
