const EMPTY = 'EMPTY'
const INVALID = 'INVALID'
const REJECTED = 'Inbox full or rejected as spam'
const BAD_REQUEST_TEAM_API_KEY = 'BAD_REQUEST_TEAM_API_KEY'
const BAD_REQUEST_TRIAL_MODE = 'BAD_REQUEST_TRIAL_MODE'
const BAD_REQUEST_UNSUPPORTED_FILE_TYPE = 'BAD_REQUEST_UNSUPPORTED_FILE_TYPE'
const BAD_REQUEST_FILENAME_TOO_LONG = 'BAD_REQUEST_FILENAME_TOO_LONG'
const BAD_REQUEST_FILENAME_EXTENSION = 'BAD_REQUEST_FILENAME_EXTENSION'
const BAD_REQUEST_RETENTION_PERIOD = 'BAD_REQUEST_RETENTION_PERIOD'
const BAD_REQUEST_CONFIRM_EMAIL = 'BAD_REQUEST_CONFIRM_EMAIL'
const BAD_REQUEST_VIRUS = 'BAD_REQUEST_VIRUS'
const BAD_REQUEST_SETUP_SEND_EMAIL = 'BAD_REQUEST_SETUP_SEND_EMAIL'
const BAD_REQUEST_EMAIL_TEMPLATE = 'BAD_REQUEST_EMAIL_TEMPLATE'
const AUTH_ERROR_CLOCK = 'AUTH_ERROR_CLOCK'
const AUTH_ERROR_INVALID_TOKEN = 'AUTH_ERROR_INVALID_TOKEN'
const RATE_LIMIT_EXCEEDED_KEY_TYPE = 'RATE_LIMIT_EXCEEDED_KEY_TYPE'
const TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS'
const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
const FILE_TOO_BIG = 'FILE_TOO_BIG'

module.exports = {
  EMPTY,
  INVALID,
  REJECTED,
  BAD_REQUEST_TEAM_API_KEY,
  BAD_REQUEST_TRIAL_MODE,
  BAD_REQUEST_UNSUPPORTED_FILE_TYPE,
  BAD_REQUEST_FILENAME_TOO_LONG,
  BAD_REQUEST_FILENAME_EXTENSION,
  BAD_REQUEST_RETENTION_PERIOD,
  BAD_REQUEST_CONFIRM_EMAIL,
  BAD_REQUEST_VIRUS,
  BAD_REQUEST_SETUP_SEND_EMAIL,
  BAD_REQUEST_EMAIL_TEMPLATE,
  AUTH_ERROR_CLOCK,
  AUTH_ERROR_INVALID_TOKEN,
  RATE_LIMIT_EXCEEDED_KEY_TYPE,
  TOO_MANY_REQUESTS,
  INTERNAL_SERVER_ERROR,
  FILE_TOO_BIG
}
