module.exports = [
  'Status',
  'Error(s)',
  'FRN',
  'SBI',
  'Payment Reference',
  'Scheme Name',
  'Scheme Short Name',
  'Scheme Year',
  'Delivery Method',
  'Business Name',
  'Address',
  'Email',
  'Filename',
  'Document DB ID',
  'Statement Data Received',
  'Notify Email Requested',
  'Statement Failure Notification',
  'Statement Delivery Notification'
]
