environment: development
environmentCode:
name: ffc-doc-statement-publisher
namespace: ffc-doc
workstream: ffc-doc
image: ffc-doc-statement-publisher

labels: {}

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-doc-statement-publisher-config-map

containerSecret:
  name: ffc-doc-statement-publisher-container-secret
  type: Opaque

deployment:
  minReplicas: 2
  maxReplicas: 3
  cpuThreshold: 80
  memoryThreshold: 80

container:
  requestMemory: 120Mi
  requestCpu: 80m
  limitMemory: 250Mi
  limitCpu: 240m
  messageQueueHost: namespace.servicebus.windows.net
  publishTopicAddress: ffc-doc-statement-publish
  publishSubscriptionAddress: ffc-doc-statement-publisher
  crmTopicAddress: ffc-doc-statement-crm
  azureStorageAccountName: ffcdoc
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  storageContainer: statements
  storageFolder: outbound
  storageReportFolder: reports
  notifyApiKey: dummy
  notifyApiKeyLetter: dummy
  notifyEmailTemplateKey: dummy
  statementReceiverApiVersion: v1
  statementReceiverEndpoint: https://ffc-doc-statement-receiver
  DelinkedIntervalNumber: 1
  DelinkedIntervalType: months
  DelinkedDayOfMonth: 15
  DelinkedDurationNumber: 1
  DelinkedDurationType: months
  SfiIntervalNumber: 1
  SfiIntervalType: months
  SfiDayOfMonth: 15
  SfiDurationNumber: 1
  SfiDurationType: months
  deliveryCheckInterval: 30000
  reportingCheckInterval: 30000
  retentionPeriodInWeeks: 78

ingress:
  server: example.com

postgresService:
  postgresDb: ffc_doc_statement_publisher
  postgresqlHost: ffc-doc-statement-publisher-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
