environment: development
environmentCode:
name: ffc-doc-statement-publisher
namespace: ffc-doc
workstream: ffc-doc
image: ffc-doc-statement-publisher

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-doc-statement-publisher-config-map

containerSecret:
  name: ffc-doc-statement-publisher-container-secret
  type: Opaque

deployment:
  minReplicas: 1
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0

container:
  requestMemory: 150Mi
  requestCpu: 120m
  limitMemory: 150Mi
  limitCpu: 120m
  messageQueueHost: namespace.servicebus.windows.net
  publishTopicAddress: ffc-doc-statement-publish
  publishSubscriptionAddress: ffc-doc-statement-publisher
  crmTopicAddress: ffc-doc-statement-crm
  azureStorageAccountName: ffcdoc
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  storageContainer: statements
  storageFolder: outbound
  notifyApiKey:
  notifyEmailTemplateKey:

postgresService:
  postgresDb: ffc_doc_statement_publisher
  postgresqlHost: ffc-doc-statement-publisher-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
