---
environment: production
environmentCode: prd
container:
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  publishTopicAddress: ffc-doc-statement-publish-prd
  publishSubscriptionAddress: ffc-doc-statement-publiher
  crmTopicAddress: ffc-doc-statement-crm-prd
  azureStorageAccountName: prdffcdocst1001
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  storageContainer: statements
  storageFolder: outbound
  storageReportFolder: reports
  statementReceiverApiVersion: v1
  statementReceiverEndpoint: https://ffc-doc-statement-receiver
  DelinkedIntervalNumber: 1
  DelinkedIntervalType: months
  DelinkedDayOfMonth: 15
  DelinkedDurationNumber: 1
  DelinkedDurationType: months
  SfiIntervalNumber: 1
  SfiIntervalType: months
  SfiDayOfMonth: 15
  SfiDurationNumber: 1
  SfiDurationType: months
  retentionPeriodInWeeks: 78
  alertTopicAddress: ffc-doc-alerting-prd
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appInsights-connectionString
        objectType: secret

  secretObjects:
    - secretName: ffc-doc-statement-publisher
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appInsights-connectionString
          key: APPLICATIONINSIGHTS_CONNECTION_STRING