#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^ffc-doc$ --format={{.Name}})" ]; then
  echo "Creating ffc-doc Docker network"
  docker network create ffc-doc
fi

if [ -n "$(docker container ls --filter label=com.docker.compose.pay.role=ffc-doc-statement-azurite --format={{.ID}})" ]; then
  echo "Azurite container already exists, skipping creation"
  args="--scale ffc-doc-statement-azurite=0"
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

docker compose down
docker compose -f docker-compose.migrate.yaml down
# Ensure container images are up to date
docker compose -f docker-compose.migrate.yaml run --rm database-up

docker compose \
  -f docker-compose.yaml \
  -f docker-compose.override.yaml \
  -f docker-compose.link.yaml \
  up $args $@
